import { IProperty, IPropertyList } from 'interfaces/property.interface'

export const defaultProperty: IProperty = {
  propertyName: '',
  displayName: '',
  description: '',
  propertyType: '',
  propertyControl: '',
  options: '',
  defaultValue: '',
}

export const propertyListState: IPropertyList[] = [
  {
    id: 1,
    isShowed: true,
    property: {
      propertyName: 'Color',
      displayName: '',
      description: '',
      propertyType: 'oneof',
      propertyControl: 'select',
      options: 'default,inherit,primary,secondary',
      defaultValue: 'default',
    },
  },
  {
    id: 2,
    isShowed: true,
    property: {
      propertyName: 'Children',
      displayName: '',
      description: '',
      propertyType: 'node',
      propertyControl: 'textarea',
      options: '',
      defaultValue: '',
    },
  },
  {
    id: 3,
    isShowed: true,
    property: {
      propertyName: 'Disabled',
      displayName: '',
      description: '',
      propertyType: 'boolean',
      propertyControl: '',
      options: '',
      defaultValue: false,
    },
  },
  {
    id: 4,
    isShowed: false,
    property: {
      propertyName: 'Disable focus ripple',
      displayName: '',
      description: '',
      propertyType: 'boolean',
      propertyControl: '',
      options: '',
      defaultValue: false,
    },
  },
  {
    id: 5,
    isShowed: false,
    property: {
      propertyName: 'Disable ripple',
      displayName: '',
      description: '',
      propertyType: 'boolean',
      propertyControl: '',
      options: '',
      defaultValue: false,
    },
  },
  {
    id: 6,
    isShowed: false,
    property: {
      propertyName: 'Full width',
      displayName: '',
      description: '',
      propertyType: 'boolean',
      propertyControl: '',
      options: '',
      defaultValue: true,
    },
  },
  {
    id: 7,
    isShowed: true,
    property: {
      propertyName: 'Mini',
      displayName: '',
      description: '',
      propertyType: 'boolean',
      propertyControl: '',
      options: '',
      defaultValue: false,
    },
  },
  {
    id: 8,
    isShowed: true,
    property: {
      propertyName: 'New property',
      displayName: '',
      description: '',
      propertyType: 'boolean',
      propertyControl: '',
      options: '',
      defaultValue: false,
    },
  },
  {
    id: 9,
    isShowed: true,
    property: {
      propertyName: 'Size',
      displayName: '',
      description: '',
      propertyType: 'oneof',
      propertyControl: 'select',
      options: 'default,small,medium,large',
      defaultValue: 'default',
    },
  },
  {
    id: 10,
    isShowed: true,
    property: {
      propertyName: 'Variant',
      displayName: '',
      description: '',
      propertyType: 'oneof',
      propertyControl: 'select',
      options: 'default,text,outlained,contained',
      defaultValue: 'contained',
    },
  },
]
